### ISSUE TITLE
Zero byte file in cookbook can't be served from filestore

### ISSUE THREAD

**Issue by oker1** [ctdk/goiardi#30]
Relevant log messages:

```
2015/01/16 14:23:41 http: panic serving 192.168.33.10:46449: runtime error: invalid memory address or nil pointer dereference
goroutine 326 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
main.fileStoreHandler(0xa374b8, 0xc20814a820, 0xc2083ea750)
	/Users/jeremy/go/src/github.com/ctdk/goiardi/file_store.go:45 +0x20d
net/http.HandlerFunc.ServeHTTP(0x7777f8, 0xa374b8, 0xc20814a820, 0xc2083ea750)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800a720, 0xa374b8, 0xc20814a820, 0xc2083ea750)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
main.(*interceptHandler).ServeHTTP(0x93b5f0, 0xa374b8, 0xc20814a820, 0xc2083ea750)
	/Users/jeremy/go/src/github.com/ctdk/goiardi/goiardi.go:283 +0xed6
net/http.serverHandler.ServeHTTP(0xc2080545a0, 0xa374b8, 0xc20814a820, 0xc2083ea750)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20814a780)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by ctdk** [comment]
Should be a straightforward fix. Thanks for finding it, I should have this one turned around over the weekend.

**Comment by ctdk** [comment]
A fix is up in 0.9.1-dev. I'll be running it against the chef-pedant tests shortly, but in the meantime if you're inclined you can check it out and see if it fixes the problem.

**Comment by oker1** [comment]
I does not seem to fix the problem, I see the same error.

**Comment by ctdk** [comment]
Hmm, strange. When I was doing it here I had an error with downloading a cookbook with a zero byte file, but after making the change downloading the cookbook worked. You did test against the 0.9.1-dev branch, right?

**Comment by oker1** [comment]
My bad, I wasn't building the project in $GOPATH, and it used the filestore module from $GOPATH. It's working now, thanks for the quick fix!

**Comment by ctdk** [comment]
Woohoo! Closing.
