### ISSUE TITLE
Unable to upload cookbook with new knife

### ISSUE THREAD

**Issue by aknarts** [ctdk/goiardi#53]
Not sure what changed, I think that knife is expecting some kind of header from the server

```
$ knife cookbook -V upload commonlib
INFO: Using configuration from /home/mistastn/RubymineProjects/chef/.chef/knife.rb
Uploading commonlib      [0.0.0]
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
INFO: Saving commonlib
ERROR: TypeError: no implicit conversion of String into Integer

```

The only line in the server log is this:
`2017/07/20 12:55:55 [DEBUG] [main] (goiardi.go:(*interceptHandler).ServeHTTP:299) Serving /cookbooks -- GET`

$ knife -v
Chef: 13.2.20
upgraded chef-dk (1.5.0-1 -> 2.0.28-1)

The cookbooks I tested are tested on the previous version of knife, and also on the chef-server where it still works. Not sure if there is further debug possible with the knife client. 

This update happened only yesterday and I guess I can roll back to the older version, so this is just heads up that something is happening.

**Comment by rmoriz** [comment]
see https://github.com/ctdk/goiardi/issues/51

**Comment by aknarts** [comment]
Yes saw the other issue and I do consider it to be the same. This is just extension of the same bug.

Just a side note, tested with the new chef-client which also fails.
```
[2017-07-20T14:19:23+00:00] DEBUG: Re-raising exception: TypeError - no implicit conversion of String into Integer
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/server_api_versions.rb:29:in `[]'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/server_api_versions.rb:29:in `min_server_version'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/versioned_api.rb:51:in `block in get_class_for'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/versioned_api.rb:47:in `select'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/versioned_api.rb:47:in `get_class_for'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/versioned_api.rb:69:in `best_request_version'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http/authenticator.rb:68:in `request_version'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http/authenticator.rb:49:in `handle_request'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:331:in `block in apply_request_middleware'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:329:in `each'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:329:in `inject'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:329:in `apply_request_middleware'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:147:in `request'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/http.rb:131:in `post'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/policy_builder/expand_node_object.rb:177:in `sync_cookbooks'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:513:in `setup_run_context'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:281:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:263:in `load'
  /usr/bin/chef-client:263:in `<main>'
```

I can close this as a duplicate. Just a last question, when can we expect a new release? Or should I build from master?

**Comment by rmoriz** [comment]
see https://github.com/ctdk/goiardi/issues/51#issuecomment-315387120

I suggest to pin to chef-12-based chef-client/chefdk for now.

**Comment by aknarts** [comment]
Well from what I understand it is "solved" by this commit https://github.com/ctdk/goiardi/commit/984daec0a7006366209a928352904d40f74d79e4 hence my question when will this make it into a release.

**Comment by rmoriz** [comment]
If you have go installed on configured just run:

```shell
go get github.com/ctdk/goiardi
```

**Comment by aknarts** [comment]
Well running this on Arch, so I can just quickly do a PKGBUILD file, I am in no rush as I just tried the updated client on one server and I can roll back there and I will just pin the chef version for now.

**Comment by ctdk** [comment]
This has been merged in (such as it is - the chef-client 13 breakage is still a thing) and released.
